### ISSUE TITLE
Move to a-b-street org

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstr#1]
Heads-up @dabreegster, we have a working package!

Not ready yet but shouldn't take too much work and I'm up for porting it when it gets to a point that it could be useful for others.

**Comment by dabreegster** [comment]
I like the package name, `abstr`. Should that also be the repository name, or is `a-b-street/abstreet` and `a-b-street/abstr` confusing? Is there any convention for denoting R libraries, like `abstr-r` or `abstr-rlang`?

**Comment by Robinlovelace** [comment]
Good question, I'll have a think... Hardest thing is thinking of names!

**Comment by Robinlovelace** [comment]
OK, looking at it there seems to be no clear convention, see https://github.com/igraph for example.

Regarding the questions, I think the risk of confusion between `abstr` and `abstreet` is low and, if a convention were needed, it could pave the way for packages like `abstpy` (or `abpy`?), `abJulia` etc.

It is possible for R package names to differ from their repo names (see the igraph example above) and if we were to go for a `-language` name, I would favour `abstreet-r` or `abstreetR` over the `abstr-*` options.

I think my mild preference would be to keep it simply as `abstr` but open minded and happy to change it. Ultimately the name is far less important than the contents + functionality of the package (which still hold much to be desired but for which I have high hopes) but it's worth thinking about before moving orgs. What do you reckon @dabreegster ?

**Comment by Robinlovelace** [comment]
Other options: rename the package `abr` or `abstreetR` and go with that - that way the repo name will match the package name still...

**Comment by dabreegster** [comment]
Thanks for looking at other options! Somehow I missed that "abstr" isn't just a prefix of "abstreet", but is "abst"+"r". I think this name is fine.

We can do the transfer now. Per https://docs.github.com/en/github/administering-a-repository/transferring-a-repository, I think you can make the request, and I can approve from the a-b-street org.

**Comment by Robinlovelace** [comment]
Just tried as followed

![image](https://user-images.githubusercontent.com/1825120/107434795-2264f080-6b23-11eb-9ec4-4ad295830366.png)

and it said:

![image](https://user-images.githubusercontent.com/1825120/107434841-34df2a00-6b23-11eb-87ce-0ec6e47013de.png)

**Comment by Robinlovelace** [comment]
I looked at https://docs.github.com/en/github/administering-a-repository/transferring-a-repository but couldn't see how to ask for permission, may have missed something...

**Comment by dabreegster** [comment]
Huh, I thought it would send me a request or something to approve. I just invited you to the a-b-street org; that makes more sense anyway.

**Comment by Robinlovelace** [comment]
Fantastic, many thanks 🎉

**Comment by Robinlovelace** [comment]
One artefact of this: I don't think I have admin powers over the package now (no cog for settings):

![image](https://user-images.githubusercontent.com/1825120/107435694-6e646500-6b24-11eb-969a-1946f514824c.png)

If you can give me admin on a per project basis - may involve creating an 'abstr' Team in the org - please do so @dabreegster. Got a good reason for accessing the settings, to change the package website to https://a-b-street.github.io/abstr/  which, amazingly, just works!

**Comment by dabreegster** [comment]
There's directly a "manage access" settings tab. I gave you admin; try now

**Comment by Robinlovelace** [comment]
Bingo!
