### ISSUE TITLE
Update new version of ab_scenario to work with ActDev

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstr#18]
Heads-up @natesheehan, after #16 was merged I think the latest version of `abstr` will no longer work with ActDev code. No big issue because we can use `abstr` 0.1.1: https://github.com/a-b-street/abstr/releases/tag/v0.1.1 with

```r
remotes::install_github("a-b-street/abstr", ref = "v0.1.1")
```

Ideally the codebase of the latest version should work with our codebase but that will require allowing origin and destination zone arguments. The best way to fix that is upstream in https://github.com/ITSLeeds/od/issues/33 I think. Let me know  Nathanael/anyone if you fancy a coding challenge, this is a big one so just asking questions and testing things will help here.

**Comment by natesheehan** [comment]
Gotcha - I've called the stable ref version in the ActDev repo for now and will get to updating for new version compatibility for early next week (#19 )

**Comment by Robinlovelace** [comment]
Heads-up @natesheehan just realised this is the issue to be working on. Could you double check you uninstalled the old version of `abstr` and restarted your R session before  running code that generated this PR https://github.com/cyipt/actdev/pull/177#pullrequestreview-703144263

I think that after https://github.com/a-b-street/abstr/commit/b03761719cca9bc8a3bb8811c1dfc6785ab2642c `abstr` should always output in the new schema.

**Comment by Robinlovelace** [comment]
Replaced by #34
