### ISSUE TITLE
Multi-destination trips

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstr#23]
Currently only single desire lines to single trips are supported. You can work around this by creating multiple desire lines but would be good to be able to represent a full day of activity, e.g. home -> work -> lunch in a cafe -> work -> home in an `sf` -> `json` object. Not sure best way of implementing it but sure it's possible.

**Comment by Robinlovelace** [comment]
Heads-up everyone, I've done a bit of writing on this and have a reproducible example that is a vignette in-the-making. First I need to know what A/B Street json schema in a minimal reproducible example should be. The 2nd JSON below is wrong I know, having an idea of what it should look like will help fix this issue.

<details>

Multi-trip activity models
================

Simple representations of transport systems based on origin-destination
data often represent daily travel patterns as a single main trip per
day, without distinguishing between multiple stages in a multi-stage
trip (walk -&gt; bus -&gt; walk -&gt; destination trips are simply
represented as bus -&gt; destination) or even multiple trips during the
course of the day (omitting the fact that many people take a lunchtime
trip to get lunch or simply to stretch their legs each day).

The concept of an ‘activity model’ aims to address these limitations by
representing the complete list of activities undertaken by people
throughout the day in the activity model. In this sense A/B Street can
be seen as an activity model.

To show how A/B Street represents activity model data, we will take a
hypothetical example, a trip from home to work and then to the park, to
lunch and then to work before returning home after work. This 5 trip
activity is more realistic that simple OD based models that just
represents people travelling from home to work (and not back again in
many cases), and is illustrated in the figure below.

![](od-sketch.png)

How to get this information into a format for modelling? This article
demonstrates how the data can be represented in R, and then converted
into a format that can be imported by A/B Street.

``` r
library(abstr)
```

In R code, this can be represented as follows:

``` r
places = tibble::tribble(
  ~name, ~x, ~y,
  "Home", -1.524, 53.819,
  "Work", -1.552, 53.807,
  "Park", -1.560, 53.812,
  "Cafe", -1.556, 53.802
)
places_sf = sf::st_as_sf(places, coords = c("x", "y"), crs = 4326)
plot(places_sf, pch = places$name)
```

![](activity_files/figure-gfm/places-1.png)

``` r
# mapview::mapview(places_sf, pch = places$name)
```

``` r
od = tibble::tribble(
  ~o, ~d, ~mode, ~departure, ~person,
  "Home", "Work", "Bike", "08:30", 1,
  "Work", "Park", "Walk", "11:30", 1,
  "Park", "Cafe", "Walk", "12:15", 1,
  "Cafe", "Work", "Walk", "12:45", 1,
  "Work", "Home", "Bike", "17:00", 1
)
od_sf = od::od_to_sf(od, places_sf)
#> 0 origins with no match in zone ids
#> 0 destinations with no match in zone ids
#>  points not in od data removed.
plot(od_sf["departure"], reset = FALSE, key.pos = 1, lwd = 6:2)
plot(places_sf$geometry, pch = places$name, add = TRUE, cex =2)
```

![](activity_files/figure-gfm/lines-1.png)

``` r
od::od_coordinates(od_sf)
```

``` r
departure_times = c(
  8.5,
  11.5,
  12.25,
  12.75,
  17
)
od_sf$departure = ab_time_normal(hr = departure_times, sd = 0.15, n = length(departure_times))
od_json1 = abstr::ab_json(desire_lines_out = od_sf[1, ], scenario_name = "activity")
od_json2 = abstr::ab_json(desire_lines_out = od_sf[1:2, ], scenario_name = "activity")
od_json = abstr::ab_json(desire_lines_out = od_sf, scenario_name = "activity")
```

``` r
ab_save(od_json1, f = "scenario1.json")
# readChar("scenario1.json", nchars = 1e9)
# file.edit("scenario1.json")
```

That results in the following file:

``` json
{
  "scenario_name": "activity",
  "people": [
    {
      "trips": [
        {
          "departure": 304770000,
          "origin": {
            "Position": {
              "longitude": -1.524,
              "latitude": 53.819
            }
          },
          "destination": {
            "Position": {
              "longitude": -1.552,
              "latitude": 53.807
            }
          },
          "mode": "Bike",
          "purpose": "Shopping"
        }
      ]
    }
  ]
}
```

What do the first 2 trips look like?

``` r
ab_save(od_json2, "scenario2.json")
# file.edit("scenario2.json")
```

``` json
{
  "scenario_name": "activity",
  "people": [
    {
      "trips": [
        {
          "departure": 304770000,
          "origin": {
            "Position": {
              "longitude": -1.524,
              "latitude": 53.819
            }
          },
          "destination": {
            "Position": {
              "longitude": -1.552,
              "latitude": 53.807
            }
          },
          "mode": "Bike",
          "purpose": "Shopping"
        }
      ]
    },
    {
      "trips": [
        {
          "departure": 415890000,
          "origin": {
            "Position": {
              "longitude": -1.552,
              "latitude": 53.807
            }
          },
          "destination": {
            "Position": {
              "longitude": -1.56,
              "latitude": 53.812
            }
          },
          "mode": "Walk",
          "purpose": "Shopping"
        }
      ]
    }
  ]
}
```

``` r
# ab_json2(desire_lines_out = od_sf, scenario_name = "activity")
```

**Comment by dabreegster** [comment]
https://github.com/a-b-street/docs/commit/75ee24c05ed25567150f16225b70037493e3aedd updates the example in docs, https://a-b-street.github.io/docs/tech/dev/formats/scenarios.html will be live in a few minutes.

The JSON in your example looks like it defines multiple people, each with one trip. The `trips` JSON list should have multiple entries. Departure time should be increasing, and destination of trip 1 should match origin of trip 2.

> In this sense A/B Street can be seen as an activity model.

Definitely. The scenario format is a simplification of what [Soundcast](https://github.com/psrc/soundcast/wiki/Outputs) provides. Their representation is more complex -- they have tours, but we flatten those.

By the way, the Soundcast [docs](https://www.psrc.org/activity-based-travel-model-soundcast) are a fantastic and detailed explanation of activity models. https://www.psrc.org/sites/default/files/shrp2_c46.pdf

**Comment by Robinlovelace** [comment]
Fantastic, I suspected this could lead to a useful update to the A/B Street docs, will take a look at some point this week, interesting problem so aiming to look sooner rather than later.

**Comment by Robinlovelace** [comment]
Quick follow-up question: how would you represent a multi-modal trip by non PT modes, e.g. driving to a cheap car park in the edge of town, getting out a folding bike and cycling into the center?

**Comment by Robinlovelace** [comment]
Work in progress: https://github.com/a-b-street/abstr/pull/64

**Comment by dabreegster** [comment]
> a multi-modal trip by non PT modes, e.g. driving to a cheap car park in the edge of town, getting out a folding bike and cycling into the center?

Trips with multiple modes in sequence like that are different than one person taking multiple trips through the day. A/B Street doesn't have direct support for the first case. Soundcast also represents this, and we just "flatten" the trips.

So I would model it as one person who takes 2 trips: drive from wherever to the car park, then bike from the car park to the center. You can fudge the departure time of the second leg of the trip. As long as it's after the departure time of the first, it'll work. Ideally you have a rough estimate of the first trip's duration that you can use, but if not, just add a fixed few minutes or something. The second trip in A/B Street will show up as "delayed" if the person hasn't reached the car park when you predict.

**Comment by Robinlovelace** [comment]
Sounds good and makes sense, reasonable fudge :+1:

**Comment by Robinlovelace** [comment]
Just to clarify, in this case, a hypothetical 2 stage trip by driving and cycling in soundcast would be converted into a 1 stage driving trip, or whichever stage is longer? Sounds like a reasonable simplifying assumption in cities where the majority of trips are single stage.

**Comment by dabreegster** [comment]
It would turn into 2 trips; we shouldn't ever totally throw away a trip from Soundcast.

https://github.com/a-b-street/abstreet/blob/e2fc59a31aa043a879a372b2350b1f42391ee740/importer/src/soundcast/popdat.rs#L269 has comments about Soundcast's model. I don't actually see a single trip using multiple modes in their docs. There is a "park and ride" case that we currently just call `TripMode::Transit`,which will mean walking to a bus.

My advice stands -- send in 2 trips in the JSON and make a best guess about the departure time

**Comment by Robinlovelace** [comment]
OK that makes sense, was checking what you meant by flattening.

**Comment by Robinlovelace** [comment]
Update on this, after the commit above we have the following. I'm now thinking a function called `ab_sf()` to convert from the `json` format to `sf` (e.g. Shapefile, GeoJSON output via GDAL), the opposite of `ab_json()`. We can test round trip between the two. Sound like a reasonable function name and plan @dabreegster and @natesheehan ?

``` r
# Aim: generate a minimal dataset corresponding to a minimal example scenario

json = jsonlite::read_json("inst/extdata/minimal_scenario2.json")
json_df = jsonlite::read_json("inst/extdata/minimal_scenario2.json", simplifyVector = TRUE)
# Try importing the data into abstreet
json_df$people$trips[[1]]
#>   departure origin.Position.longitude origin.Position.latitude
#> 1      1000                 -122.3037                 47.63728
#> 2  10000000                 -122.3191                 47.63786
#>   destination.Position.longitude destination.Position.latitude mode    purpose
#> 1                      -122.3191                      47.63786 Bike       Meal
#> 2                      -122.3076                      47.63948 Walk Recreation
trip_data = dplyr::bind_rows(json_df$people$trips, .id = "id")
trip_data
#>   id departure origin.Position.longitude origin.Position.latitude
#> 1  1      1000                 -122.3037                 47.63728
#> 2  1  10000000                 -122.3191                 47.63786
#> 3  2     11000                 -122.3037                 47.63828
#> 4  2  10010000                 -122.3191                 47.63886
#>   destination.Position.longitude destination.Position.latitude mode    purpose
#> 1                      -122.3191                      47.63786 Bike       Meal
#> 2                      -122.3076                      47.63948 Walk Recreation
#> 3                      -122.3191                      47.63886 Bike       Meal
#> 4                      -122.3076                      47.64048 Walk Recreation
# unhelpful flat format
# trip_data_unnested = tidyr::unnest(trip_data, cols = c(origin, destination))
names(trip_data)
#> [1] "id"          "departure"   "origin"      "destination" "mode"       
#> [6] "purpose"

# code below could be generalised to a json_to_sf() function
linestrings = od::odc_to_sfc(cbind(
  trip_data$origin$Position$longitude,
  trip_data$origin$Position$latitude,
  trip_data$destination$Position$longitude,
  trip_data$destination$Position$latitude
))
# mapview::mapview(linestrings)


sf_data = subset(trip_data, select = -c(origin, destination))
sf_linestring = sf::st_sf(
  sf_data,
  geometry =linestrings
)

plot(sf_linestring)
```

![](https://i.imgur.com/S1XO5Uf.png)

<sup>Created on 2021-09-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Robinlovelace** [comment]
Observation suggesting that it may be worth simplifying the output of `ab_json()` so it's just a list:

```
# Aim: generate a minimal dataset corresponding to a minimal example scenario

json = jsonlite::read_json("inst/extdata/minimal_scenario2.json")
json$scenario_name
json_df = jsonlite::read_json("inst/extdata/minimal_scenario2.json", simplifyVector = TRUE)
# Try importing the data into abstreet
json_df$people$trips[[1]]
trip_data = dplyr::bind_rows(json_df$people$trips, .id = "id")
trip_data
# unhelpful flat format
# trip_data_unnested = tidyr::unnest(trip_data, cols = c(origin, destination))
names(trip_data)

# code below could be generalised to a json_to_sf() function
linestrings = od::odc_to_sfc(cbind(
  trip_data$origin$Position$longitude,
  trip_data$origin$Position$latitude,
  trip_data$destination$Position$longitude,
  trip_data$destination$Position$latitude
))
# mapview::mapview(linestrings)


sf_data = subset(trip_data, select = -c(origin, destination))
sf_linestring = sf::st_sf(
  sf_data,
  geometry = linestrings
)

plot(sf_linestring)

json2 = ab_json(desire_lines_out = sf_linestring, scenario_name = "minimal2")
identical(json, json2)
waldo::compare(json, json2)
```

<details>

# Aim: generate a minimal dataset corresponding to a minimal example scenario

json = jsonlite::read_json("inst/extdata/minimal_scenario2.json")
json$scenario_name
json_df = jsonlite::read_json("inst/extdata/minimal_scenario2.json", simplifyVector = TRUE)
# Try importing the data into abstreet
json_df$people$trips[[1]]
trip_data = dplyr::bind_rows(json_df$people$trips, .id = "id")
trip_data
# unhelpful flat format
# trip_data_unnested = tidyr::unnest(trip_data, cols = c(origin, destination))
names(trip_data)

# code below could be generalised to a json_to_sf() function
linestrings = od::odc_to_sfc(cbind(
  trip_data$origin$Position$longitude,
  trip_data$origin$Position$latitude,
  trip_data$destination$Position$longitude,
  trip_data$destination$Position$latitude
))
# mapview::mapview(linestrings)


sf_data = subset(trip_data, select = -c(origin, destination))
sf_linestring = sf::st_sf(
  sf_data,
  geometry = linestrings
)

plot(sf_linestring)

json2 = ab_json(desire_lines_out = sf_linestring, scenario_name = "minimal2")
identical(json, json2)
waldo::compare(json, json2)

**Comment by natesheehan** [comment]
> Update on this, after the commit above we have the following. I'm now thinking a function called `ab_sf()` to convert from the `json` format to `sf` (e.g. Shapefile, GeoJSON output via GDAL), the opposite of `ab_json()`. We can test round trip between the two. Sound like a reasonable function name and plan @dabreegster and @natesheehan ?

`ab_sf()`  sounds like the right name!

**Comment by Robinlovelace** [comment]
![Peek 2021-09-13 21-22](https://user-images.githubusercontent.com/1825120/133151789-31f59f44-e3a5-483c-b28a-1b7caeb7dacf.gif)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/133152963-a57d3812-e05c-4acb-8969-5464ab2b5d74.png)
