### ISSUE TITLE
Issue with documentation of `montlake_buildings`

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstr#28]
As shown below:

![image](https://user-images.githubusercontent.com/1825120/123678919-d18a3600-d83e-11eb-8ed8-0973fa6459d9.png)

Heads-up @tnederlof I've got a fix brewing...

**Comment by Robinlovelace** [comment]
https://a-b-street.github.io/abstr/reference/montlake_buildings.html

**Comment by tnederlof** [comment]
Thank you! New to documenting data but learning.
