### ISSUE TITLE
Regenerate actdev scenarios

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstr#29]
As a followup to #19, we need to regenerate the scenario JSON files for actdev -- https://github.com/cyipt/actdev/blob/main/data-small/allerton-bywater/scenario_base.json and the others. Wasn't sure whether to file that issue here or in the actdev repo. Until then, the base & go active scenarios in A/B Street will disappear, because I also made an internal binary format change that requires me to regenerate from the actdev repo's JSON. (This won't affect the live actdev deployment, of course, but it blocks updating it.)

**Comment by tnederlof** [comment]
I’m not very familiar with actdev but happy to help. How were these scenarios originally generated? Is there a script that was run that I can update with the current ab_scenario?

**Comment by Robinlovelace** [comment]
Aha that makes sense, thanks Dustin. And many thanks @tnederlof for the offer of help that would be amazing.

The starting point would be to follow this great tutorial by @natesheehan : https://github.com/cyipt/actdev/blob/main/code/tests/add-new-site.md

Basically this comes down to running this script in the repo's root directory: https://github.com/cyipt/actdev/blob/main/code/build.R note also this issue https://github.com/a-b-street/abstr/issues/18 that may need looking at, I think we will still need to tweak either the ActDev or abstr code for the new version to work but shouldn't be too much work. Good test site: `lcid` close to Leeds city centre and a great example of sustainable and attractive housing.

**Comment by natesheehan** [comment]
Once I have rerun the work for https://github.com/cyipt/actdev/issues/179, I think we can close this issue too?

**Comment by Robinlovelace** [comment]
> Once I have rerun the work for [cyipt/actdev#179](https://github.com/cyipt/actdev/issues/179), I think we can close this issue too?

I think so!

**Comment by Robinlovelace** [comment]
Closing here because the work in this repo is I think done, as documented in #34. Linked to and partly superseded by https://github.com/cyipt/actdev/issues/179
