### ISSUE TITLE
Update README to include latest example (not lcid)

### ISSUE THREAD

**Issue by natesheehan** [a-b-street/abstr#30]
Discussed with @Robinlovelace , since the great work by @tnederlof , we should update the README to include the latest example instead of Leeds.

**Comment by Robinlovelace** [comment]
Idea: GIFs of the input data before/after a model in R is implemented to show the idea.

**Comment by natesheehan** [comment]
Should we close this issue now?

**Comment by Robinlovelace** [comment]
Job done, many thanks Nathanael!
