### ISSUE TITLE
Add GIF to readme showing what the data looks like when imported into A/B Street

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstr#37]
That will get the message across: turn your R data frames into interactive transport simulations! You up for giving this a go @natesheehan ?

**Comment by natesheehan** [comment]
![df_to_sim_final](https://user-images.githubusercontent.com/22789869/128744160-1b5381e8-c174-4c26-afe2-5bf1c7968ddc.gif)

**Comment by natesheehan** [comment]
@Robinlovelace hows does this look for an initial gif?

**Comment by natesheehan** [comment]
Would we add the giff to the data-raw folder? Or should we host it elsewhere?

**Comment by Robinlovelace** [comment]
Pretty good but can it show the process of moving the .json file into the right place and selecting it? Sorry to be picky but those are the bits that tripped me up first time I tried (and will probably trip me up again)! In terms of GIF location, no they can just live here and be referred to but their URL, e.g. https://user-images.githubusercontent.com/22789869/128744160-1b5381e8-c174-4c26-afe2-5bf1c7968ddc.gif 

The fewer big files that are committed to the git repo the better in general.

**Comment by natesheehan** [comment]
![montlake_1](https://user-images.githubusercontent.com/22789869/128903844-a84c71bd-0d9e-4756-8059-79f34deb539d.gif)

**Comment by natesheehan** [comment]
![montlake_202](https://user-images.githubusercontent.com/22789869/128907563-4aa95b30-a98d-4fbc-9275-97e0b30dd227.gif)

**Comment by Robinlovelace** [comment]
Looking good!

**Comment by natesheehan** [comment]
Personally prefer the second one, think it runs a lil smoother as I have edited out some frames. 

I think once we master the process of one-shotting, it could also make for a nice video/screencast!
