### ISSUE TITLE
Check that the package is ready for CRAN

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstr#38]
Ideal command for this:

```r
devtools::check_win_devel()
```

**Comment by natesheehan** [comment]
```{r}

pdflatex not found! Not building PDF manual.
√  checking for file 'C:\Users\natha\OneDrive\Documents\abstr/DESCRIPTION' ...
-  preparing 'abstr': (455ms)
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'abstr_0.2.1.tar.gz'
   
√ [2021-08-09] Check <rob00x@gmail.com> for a link to results in 15-30 mins (~06:27 PM).

```

**Comment by natesheehan** [comment]
I think results will be sent your way soon - I may have run this a couple of times so you may have a couple of emails!

**Comment by Robinlovelace** [comment]
Fantastic, will take a look now.

**Comment by Robinlovelace** [comment]
Here are the results: https://win-builder.r-project.org/GydEVxY2rAxO/

**Comment by Robinlovelace** [comment]
CRAN is right on this


https://a-b-street.github.io/docs/dev/formats/scenarios.html#example no longer exists. Guess that should be replaced with https://a-b-street.github.io/docs/tech/dev/formats/scenarios.html

**Comment by natesheehan** [comment]
Gotcha - I can push a change for the URL - there also seems to be an error/note with regards  to the title field, however, the suggestion looks a little bit **funky**

```
The Title field should be in title case. Current version is:
'R Interface to the A/B Street Transport System Simulation Software'
In title case that is:
'R Interface to the a/B Street Transport System Simulation Software'
````

**Comment by Robinlovelace** [comment]
> Gotcha - I can push a change for the URL

No worries, already fixed :tada: in https://github.com/a-b-street/abstr/commit/4e8a32d52b046bbe63dc601183f01f68df3de6bd



> there also seems to be an error/note with regards to the title field, however, the suggestion looks a little bit **funky**

Agreed, we can push back on that, unless CRAN want to change the name of Dustin's software...
