### ISSUE TITLE
Release to CRAN

### ISSUE THREAD

**Issue by natesheehan** [a-b-street/abstr#44]
Get abstr released to CRAN 🎉 

- [x] Run `R CMD check` and fix any issues
- [x]  Test for all environments
- [x] Update documentation
- [x] Define release version
- [x] Create badge?
- [x]  Update news.md 
- [x]  Update cran-comments.md
- [x]  Send to CRAN
----
@Robinlovelace anything else we should add to this checklist?

**Comment by natesheehan** [comment]
Currently working through warnings, latest one I am trying to bosh:
```> checking files in 'vignettes' ... WARNING
  Files in the 'vignettes' directory but no files in 'inst/doc':
    'montlake_seattle.Rmd'
  Package has no Sweave vignette sources and no VignetteBuilder field.```

**Comment by Robinlovelace** [comment]
Not sure what's going on there. I think the most important vignette will be 'Getting started with abstr' which will be created in the right place by `pkgdown` when the content exists in a file called `vignettes/abstr.Rmd`.

> To see the vignette for a specific package, use the argument, browseVignettes("packagename"). Each vignette provides three things: the original source file, a readable HTML page or PDF, and a file of R code. You can read a specific vignette with vignette(x), and see its code with edit(vignette(x)). To see vignettes for a package you haven’t installed, look at its CRAN page, e.g., https://cran.r-project.org/web/packages/dplyr.

Source: https://r-pkgs.org/vignettes.html

**Comment by natesheehan** [comment]
```  WARNING
  'qpdf' is needed for checks on size reduction of PDFs```

Next warning

**Comment by natesheehan** [comment]
Hmm from some web scrapping seems like this might be a Windows 10 issue when running R version > 4.0

**Comment by Robinlovelace** [comment]
That shouldn't affect cran submission.

**Comment by natesheehan** [comment]
What version of R are you running on your Ubuntu machine @Robinlovelace? 

Should I also ask a friend with Mac to test for us too?

```
## Test Environments
* Local Windows, R 4.0.4
* Local Ubuntu, R 

## R CMD check results

There were no ERRORs, NOTEs or WARNINGs. 
  
## Downstream dependencies

No downstream dependencies as package is new.

```

**Comment by natesheehan** [comment]
@Robinlovelace what should we add in https://github.com/a-b-street/abstr/blob/main/NEWS.md ? The 0.2.1 notes still feel pretty relevant, however, we could also add in: 

"New Vignette to reproduce the datasets based on the Montlake area in Seatle"
"New Vignette to reproduce the datasets based on the Leeds climate district in the UK"
"Add cran-comments.md file to track cran submissions"
"Update maintainer roles"

**Comment by Robinlovelace** [comment]
> Should I also ask a friend with Mac to test for us too?

No need, it's tested on Mac builds (or will be when GitHub actions are revived, they have been degraded for the last day or so): https://github.com/a-b-street/abstr/blob/main/.github/workflows/R-CMD-check.yaml

**Comment by Robinlovelace** [comment]
> The 0.2.1 notes still feel pretty relevant, however, we could also add in:
> 
> "New Vignette to reproduce the datasets based on the Montlake area in Seatle"
> "Add cran-comments.md file to track cran submissions"
> "Update maintainer roles"

:+1:
