### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstr#6]
Currently the package has many dependencies. There are advantages of depending on fewer things so will aim to follow the 'tinyverse' principles: http://www.tinyverse.org/

First package on the hit list: `dplyr` which is big, has many sub-dependencies and takes a long time to install.

**Comment by Robinlovelace** [comment]
> Is the aim to rewrite these as base-r functions?

Correct. A fun and potentially rewarding refactoring mission!

**Comment by natesheehan** [comment]
Sounds like a plan! I should have some time to look at this at the end of the week/early next week 🚀

**Comment by natesheehan** [comment]
base r functions replacing dplyr  -> https://github.com/a-b-street/abstr/pull/14

**Comment by Robinlovelace** [comment]
Job done :tada:
