### ISSUE TITLE
Exeter example

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstr#67]
Already done in #65 with tweaks in #66. Opening this issue for to track progress and share info, learned lots in the process.

**Comment by Robinlovelace** [comment]
Illustration of selecting a new scenario

![image](https://user-images.githubusercontent.com/1825120/131586308-212caee2-3ebe-48f4-8e15-39efacedf3b4.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/131586413-c91cb53e-9b19-4d98-8e7b-d46a2f6a5845.png)

**Comment by Robinlovelace** [comment]
![Peek 2021-09-01 00-06](https://user-images.githubusercontent.com/1825120/131586989-6ac002e0-55b0-4124-817e-4fa999421100.gif)

**Comment by Robinlovelace** [comment]
Here's another GIF, compressed this time (CRAN checks do not like large embedded gifs).

**Comment by Robinlovelace** [comment]
![navigation-small](https://user-images.githubusercontent.com/1825120/132119399-a97811a3-94fe-4015-a90e-f51ebe745e4d.png)

**Comment by Robinlovelace** [comment]
Heads-up @natesheehan I think there could be a better GIF, just try to make one that is less than ~2MB (not easy)!

**Comment by Robinlovelace** [comment]
![abstr](https://user-images.githubusercontent.com/1825120/132120072-29a756a8-c858-488c-aec8-f5c55aecec48.gif)

**Comment by natesheehan** [comment]
Exeter is looking good! 
It's certainly quite hard to get a small gif size showing the whole process. Maybe a video would also work for this, I am happy to set up a Youtube with a full demo?

**Comment by Robinlovelace** [comment]
> Maybe a video would also work for this, I am happy to set up a Youtube with a full demo?

:+1: :+1: :+1:

**Comment by Robinlovelace** [comment]
Anything else need to be done on this? Suspect we can close it now the `inst/docs` folder has gone below 10 MB...

**Comment by natesheehan** [comment]
Nope dont think so, lets close this and I will make a separate issue for the videos
