### ISSUE TITLE
Organise the first abstr hackathon

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstr#69]
Albeit a small 1 hr one, 15th September at midday UK time.

**Comment by natesheehan** [comment]
I am going to close this after the inspiring hackathon from yesterday!

**Comment by Robinlovelace** [comment]
Good shout. Done for sure :+1: 

One question, should we link to the resulting video when available (hopefully pretty soon)?

**Comment by natesheehan** [comment]
Oh yes, we could create a section on either the GitHub or website listing talks/presentations?
