### ISSUE TITLE
Add minimal example dataset from São Paulo

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstr#70]
Heads-up @lucasccdias as discussed today. May be best to put the data in this repo. I can help with that but are you up for a first go? Perhaps based on examples with ~2 and ~20 agents in a single part of the city. I can provide support on getting the data into the package, based on this: https://r-pkgs.org/data.html

**Comment by lucasccdias** [comment]
Sure! How is the best way of doing this? Can I just add these new data in the `./data/` folder and make a PR following the link you sent?

**Comment by Robinlovelace** [comment]
Fantastic, thanks for stepping in. Best way probably is to fork the repo onto your account, clone it onto your computer, open the project, and then do something like

```r
file.edit("data-raw/sao-paulo-activity-data.Rmd")
```

If you type in reproducible code there, ideally starting with downloading the data from a public URL, you can add the script and the file produced with the following function:

```r
usethis::use_data(sao_paul_activity_df_minimal)
```

And then commit the result.

**Comment by Robinlovelace** [comment]
Or you could do it as an R script. Good example: https://github.com/a-b-street/abstr/blob/main/data-raw/montlake-test-data.R

**Comment by lucasccdias** [comment]
I almost there. Just one more question: what do you mean by "single part of the city"? I am selecting just people that live in the São Paulo municipality. Is this too broad? What would be better?

**Comment by Robinlovelace** [comment]
>  I am selecting just people that live in the São Paulo municipality. Is this too broad? What would be better? 

Another good question. What I mean is that the activity space of the agents in the minimal example isn't too big. If they can do all there activities within a 5km radius of the city centre, or some other point, that would be good I think. That suggestion is just for visualisation purposes and is not essential.

**Comment by natesheehan** [comment]
Should we close this or is there any more work needed for the data frames? 

Also @lucasccdias it would be awesome if you could provide some details on column names/values as my Brazilian is pretty dusty!

**Comment by lucasccdias** [comment]
Sure! I'll do this, @natesheehan . But what would be the best way of doing this? Add labels in English in the data.frame? Upload a dictionary file or a documentation file?

**Comment by natesheehan** [comment]
Great stuff - I think it's fine to keep the labels in Brazilian, but maybe a documentation file like we have here https://github.com/a-b-street/abstr/blob/main/R/montlake_od.R

**Comment by Robinlovelace** [comment]
Currently I cannot see the data documented here: https://a-b-street.github.io/abstr/reference/index.html

We can close this issue when `sao_paulo_...` objects appear and are well documented there.

**Comment by lucasccdias** [comment]
@Robinlovelace @natesheehan I just made a PR with two documentation files, one for each data.frame.

**Comment by Robinlovelace** [comment]
Great work, will take a look...

**Comment by Robinlovelace** [comment]
This is now done as can be seen here: https://a-b-street.github.io/abstr/reference/sao_paulo_activity_df_2.html

Next steps I think: print the data in a new `@examples` section and add Lucas to the author list, assuming they're happy with that... Minor point: I think the info in https://a-b-street.github.io/abstr/reference/sao_paulo_activity_df_2.html and https://a-b-street.github.io/abstr/reference/sao_paulo_activity_df_20.html would be better on the same page.
