### ISSUE TITLE
Republish abstr to CRAN

### ISSUE THREAD

**Issue by natesheehan** [a-b-street/abstr#90]

**Comment by Robinlovelace** [comment]
Well spotted and looks like it's been resubmitted. Keep us posted with the outcome! While we're on version change, any new functionality in the pipeline with the 'scenario.json' schema or other stuff we should be aware of @dabreegster ? Thanks!

**Comment by dabreegster** [comment]
Nope, no schema changes there

**Comment by Robinlovelace** [comment]
Heads-up @natesheehan https://github.com/ITSLeeds/pct/issues/108 is now self fixed so I think this can progress, if that was a barrier...

**Comment by natesheehan** [comment]
Perfecto - I will send `abstr` to CRAN now!

**Comment by natesheehan** [comment]
https://github.com/a-b-street/abstr/commit/0f74e8cde0288009afdbae3d4e069c9dece9b3d2

**Comment by natesheehan** [comment]
4.0.1 has been sent to CRAN 🎆

**Comment by Robinlovelace** [comment]
:tada:
